apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-pod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QHuyNguyen/k8s_templates.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default